#ifndef QSIMPLECRYPTO_GLOBAL_H
#define QSIMPLECRYPTO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSIMPLECRYPTO_LIBRARY)
#  define QSIMPLECRYPTO_EXPORT Q_DECL_EXPORT
#else
#  define QSIMPLECRYPTO_EXPORT Q_DECL_IMPORT
#endif

#endif // QSIMPLECRYPTO_GLOBAL_H
